services:
  web:
    build: .
    ports:
      - ${EXPOSE_PORT}:8000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata/"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - warehouse_manager_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
      
volumes:
  warehouse_manager_db-data:
